esphome:
  name: xstate-display

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret apiPass

ota:
  password: !secret otaPass

wifi:
  ssid: !secret wifiSSID
  password: !secret wifiPass
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xstate-Display Fallback Hotspot"
    password: !secret fallbackPass

captive_portal:

deep_sleep:
  run_duration: 30s
  sleep_duration: 10min

switch:
  - platform: restart
    name: "Inkplate Reboot"
    id: reboot

  - platform: gpio
    id: battery_read_mosfet
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      inverted: true

script:
  - id: update_display
    then:
      - lambda: |-
          const uint16_t width = 800;
          const uint16_t height = 600;

          id(inkplate_display).clear();
          id(inkplate_display).fill(COLOR_ON);
          id(inkplate_display).image(30, 280, id(xhain_logo));
          id(inkplate_display).print(610, 310, id(politics_32), COLOR_OFF, TextAlign::TOP_LEFT, "x-hain.de");
          id(inkplate_display).qr_code(600, 350, id(xhain_homepage), Color(0,0,0), 8);
          id(inkplate_display).printf(400, 100, id(politics_96), COLOR_OFF, TextAlign::TOP_CENTER, "%s", id(current_state).state.c_str());
          if (id(system_status).state) {
            id(inkplate_display).print(width, 580, id(politics_20), COLOR_OFF, TextAlign::TOP_RIGHT, "Online");
          } else {
            id(inkplate_display).print(width, 580, id(politics_20), COLOR_OFF, TextAlign::TOP_RIGHT, "Offline");
          }
          id(inkplate_display).display();

sensor:
  - platform: adc
    id: battery_voltage
    update_interval: never
    attenuation: 11db
    pin: 35
  - platform: template
    name: "Inkplate Battery Voltage"
    lambda: |-
      id(battery_read_mosfet).turn_on();
      delay(1);
      float adc = id(battery_voltage).sample();
      id(battery_read_mosfet).turn_off();
      return adc;
    filters:
      - multiply: 2

text_sensor:
  - platform: homeassistant
    entity_id: select.xstate
    id: current_state
    on_value:
      then:
        - script.execute: update_display

image:
  - file: "xhain.png"
    id: xhain_logo
    resize: 300x300

qr_code:
  - id: xhain_homepage
    value: https://x-hain.de

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

binary_sensor:
  - platform: status
    name: "Inkplate Status"
    id: system_status
    on_state:
      then:
        - script.execute: update_display


font:
  - file: "PoliticsHead.ttf"
    id: politics_96
    size: 88
  - file: "PoliticsHead.ttf"
    id: politics_32
    size: 32
  - file: "PoliticsHead.ttf"
    id: politics_20
    size: 20


display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: false
  update_interval: 1d
  rotation: 180

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5

  lambda: id(update_display).execute();

